[package]
name = "butcher"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
colored = "*"
flate2 = "*"
log = "0.4"
env_logger = "0.9.0"
simple_logger = "4.2.0"
levenshtein_automata = "0.2.1"